Add wave-3

diff --git a/install/helm/wave-0/templates/configmaps.yaml b/install/helm/wave-0/templates/configmaps.yaml
--- a/install/helm/wave-0/templates/configmaps.yaml
+++ b/install/helm/wave-0/templates/configmaps.yaml
@@ -2,12 +2,32 @@
 apiVersion: v1
 kind: ConfigMap
 metadata:
-  name: bootstrap-script-minio
+  name: bootstrap-scripts
   {{- if .Values.annotations }}
   annotations: {{- toYaml .Values.annotations | nindent 4 }}
   {{- end }}
 data:
-  create-bucket.sh: |-
+  start-build.sh: |-
+    #!/bin/sh
+    set -eu
+    
+    echo "Starting build for $BC_NAME..."
+    
+    # Start the build and get the build name (e.g., "my-app-1")
+    BUILD_NAME=$(oc start-build $BC_NAME -n <your-namespace> --follow=false -o=jsonpath='{.metadata.name}')
+    
+    if [ -z "$BUILD_NAME" ]; then
+      echo "Failed to start build."
+      exit 1
+    fi
+    
+    echo "Build $BUILD_NAME started. Waiting for it to complete..."
+    
+    # Wait for the build to complete or fail
+    oc wait --for=condition=Complete --timeout=5m build/$BUILD_NAME -n <your-namespace>
+    
+    echo "✅ Build $BUILD_NAME completed successfully."  
+  minio-create-buckets.sh: |-
     #!/bin/sh
     set -eu
 
